name: mariomonday

services:
  db:
    container_name: database_server
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
  app:
    container_name: backend_server
    depends_on:
      - db
    build:
      context: .
      dockerfile: containerfile
    ports:
      - "8080:8080"